### ISSUE TITLE
Kann Projekt nicht mehr starten -> DisallowedHost at / Invalid HTTP_HOST header: '127.0.0.1:8000'. 

### ISSUE THREAD

**Issue by BlackPyro1994** [techkruste/stimmungspegel#1]
DisallowedHost at / HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.

Wenn ich "localhost:8000" versuche komme ich zwar wieder auf die Seite. 
Aber die Index Seite zeigt dann "Irgendetwas ist schief gelaufen… Sorry." an.

**Comment by techkruste** [comment]
Hab die `settings.py` angepasst, sollte jetzt wieder gehen.

**Comment by BlackPyro1994** [comment]
Komme jetzt wieder auf die Seite über 127.0.0.1:8000. Jedoch läd die Liste nicht und nur die Spinner Animation ist zu sehen. 

![2017-07-03 16-38-37 89](https://user-images.githubusercontent.com/7514906/27797534-57f923fc-600e-11e7-9368-0b5cc6090e59.png)

**Comment by techkruste** [comment]
Bei mir funktioniert alles

**Comment by BlackPyro1994** [comment]
Ist die Version vom letzten Pull. (aktuellste)

![2017-07-03 16-51-18 90](https://user-images.githubusercontent.com/7514906/27797978-dddcb41a-600f-11e7-8ccf-6ace4c318b68.png)

**Comment by techkruste** [comment]
So sieht's bei mir aus:
![screenshot_20170703_165131](https://user-images.githubusercontent.com/4093606/27798020-03768dae-6010-11e7-8284-b4575bcaa682.png)

**Comment by BlackPyro1994** [comment]
Hmmm ... Also "migrate" auf manage.py ( falls ich es richtig gemacht habe ) hat nichts gebracht.

![2017-07-03 16-56-32 91](https://user-images.githubusercontent.com/7514906/27798199-aa2789fa-6010-11e7-98c3-21b70cda9a9e.png)

**Comment by techkruste** [comment]
Nach der Migration musst du noch das Script `populate_db.py` ausführen, sonst sind keine Datensätze in der DB

**Comment by BlackPyro1994** [comment]
![2017-07-03 17-06-39 94](https://user-images.githubusercontent.com/7514906/27798606-2f9fe61c-6012-11e7-8e0b-774a5b56e06d.png)

![2017-07-03 17-06-24 93](https://user-images.githubusercontent.com/7514906/27798609-339a3d30-6012-11e7-88fa-b3c7de6188da.png)

![2017-07-03 17-05-01 92](https://user-images.githubusercontent.com/7514906/27798610-34ff091c-6012-11e7-826a-aa098b19a0f9.png)

Um das Projekt wieder zu starten muss ich doch "admin.py" laufen lassen, oder ??
Falls ja , kommen dort aber jetzt auch Fehler :(

**Comment by techkruste** [comment]
Wie wär's mit `python manage.py runserver`? ;)
Ich wollte mich ja eigentlich jetzt um die scheiß Audiosnippets kümmern…

**Comment by BlackPyro1994** [comment]
Ah okay. Jo mach mal erst die AudioSnippets.
